set-option -g prefix None
unbind-key C-b
bind-key -n C-a if-shell '$HOME/.local/bin/tmux-client-is-wezterm #{client_pid}' {
  send-keys C-a
} {
  switch-client -T prefix
}
bind-key -T prefix C-a send-keys C-a
